version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      args:
        - NODE_ENV=production
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
      - osrm
  redis:
    container_name: redis
    image: redis:5-alpine
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: mdillon/postgis
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eliefere
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
  osrm:
    container_name: osrm
    image: osrm/osrm-backend
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /home/gonzo/workspace/routing_machine/data:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/baden-wuerttemberg-latest.osrm"
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
