default:
  type: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  database: ${DB_DATABASE_NAME}
  synchronize: true
  logging: true
  entities:
    - dist/**/*.entity.js
  migrations:
    - dist/database/migrations/**/*.js
  subscribers:
    - dist/database/subscriber/**/.js
  cli:
    entitiesDir: src
    migrationsDir: database/migrations
    subscribersDir: database/subscriber
