version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  node: circleci/node@3.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build Docker image
          command: docker-compose build eliefere:$CIRCLE_SHA1 .
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: heroku container:push web
  deploy:
    executor: node/default
    steps:
      - run: heroku container:release web
workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
