version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  node: circleci/node@3.0.1
jobs:
  build-and-maybe-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker image
          command: |
            docker build -t eliefere .
            docker images
workflows:
  heroku_deploy:
    jobs:
      - build-and-maybe-test
      - heroku/deploy-via-git
