version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  node: circleci/node@3.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
#          cache-path: node_modules
  heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - setup_remote_docker
      - run:
          name: Heroku Container Login
          command: heroku container:login
      - run:
          name: Heroku Container push
          command: heroku container:push --app eliefere web
      - run:
          name: Heroku Container release
          command: heroku container:release --app eliefere web
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku:
          requires:
            - build
