version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  node: circleci/node@3.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
  heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - setup_remote_docker
      - run:
          command: heroku container:login
      - run:
          command: heroku container:push --app eliefere web
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku:
          requires:
            - build
